### ISSUE TITLE
Pitch & bearing control throws hundreds of errors

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-profiles#110]
Using the pitch/bearing control in any MapboxGL map throws hundreds of these errors:
`Uncaught RangeError: Maximum call stack size exceeded`

Not sure if it's impacting performance or reliability, but it's probably not a good thing. We should investigate.

**Comment by jorgeh01** [comment]
@allthesignals check if resolved

**Comment by hannahkates** [comment]
Seems resolved.
