### ISSUE TITLE
Returned 4 different results in Projects section for the same CD 

### ISSUE THREAD

**Issue by CeciliaCY** [NYCPlanning/labs-community-profiles#416]
In the same browser, it returned 4 different results when I clicked Mn05 first, then clicked other CDs, then clicked back Mn05. The most weird part is that it returned "21 east 12th street" which is in Mn02 in the completed application section (see the second image in the attached screenshot)

![screenshot-mn05](https://user-images.githubusercontent.com/30835953/30607457-12953932-9d43-11e7-9048-3c08e66372fc.jpg)

**Comment by allthesignals** [comment]
Thank you for the thorough issue report, @CeciliaCY - we will investigate for our next release.

**Comment by allthesignals** [comment]
@CeciliaCY I'm going through closing old issues, I think I implemented a fix for this, but are you able to reproduce? 

#454 relates here, we have some handling for this, but I want to make sure I didn't miss something.

**Comment by CeciliaCY** [comment]
@allthesignals Had a quick test, I didn't see such issue again.

**Comment by allthesignals** [comment]
Thanks!
