### ISSUE TITLE
Empty floodplain chart boxes

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-profiles#425]
Add N/A where no data appears in floodplain charts for buildings in floodplain, DUs in floodplain, building age, basements, and building adjacency

**Comment by allanz-dcp** [comment]
Actually - let's use "0" for the Building and Dwelling Unit tables since most of the CDs with no floodplain structures already utilize that. Thanks for flagging

**Comment by docmarionum1** [comment]
Agreed.  The first district I looked at (BK14) is out of the floodplain and I thought those charts were broken.

**Comment by hannahkates** [comment]
Closing, this appears to already be implemented: https://communityprofiles.planning.nyc.gov/brooklyn/6#floodplain
