### ISSUE TITLE
Updated Population counts in Floodplain chart (Poplation columns, Bronx population figures, commas)

### ISSUE THREAD

**Issue by allanz-dcp** [NYCPlanning/labs-community-profiles#426]
Updated floodplain table attached

Two new columns in the data: current_fp_population; future_fp_population

n. Should reference the figures that populate in "Population". Bronx populations have been corrected. Thousand separator commas added/

[Community_District_Profiles_Floodplain_Tables_Final_092017.zip](https://github.com/NYCPlanning/labs-community-portal/files/1322712/Community_District_Profiles_Floodplain_Tables_Final_092017.zip)

**Comment by allthesignals** [comment]
@allanz-dcp I need to know which columns have been updated in order to merge this in. Thanks!

**Comment by allthesignals** [comment]
@allanz-dcp this should be resolved now. `current_fp_pop` and `future_fp_pop` replaced with the values of `current_fp_population` and `future_fp_population`.

**Comment by allanz-dcp** [comment]
@allthesignals Thanks! Is there a quick fix to get the population figures to use the format 36K instead of 36269? Seems cleaner and more suitable for pop figures

**Comment by hannahkates** [comment]
Closing, appears to all be resolved.
