### ISSUE TITLE
not working in Safari and Chrome in iPhone 7 Plus

### ISSUE THREAD

**Issue by ceciliaITpub** [NYCPlanning/labs-community-profiles#432]
CP isn't working properly in Safari and Chrome in iPhone 7 Plus. The page was loaded successfully, but when you click the CD, at first, no response, then when you click another CD, the page started reloading and reloading and crashed in the end with message ""A problem repeatly occurred on "http://comm..........".

iOS - 10.3.3

**Comment by chriswhong** [comment]
Thanks for the tip!  We'll take a look.

**Comment by allthesignals** [comment]
@CeciliaCY do you know if this is still an issue? Could you give it a try? I think recent upgrades may have improved the memory issues.

**Comment by CeciliaCY** [comment]
@allthesignals It's working fine in my iPhone X

**Comment by allthesignals** [comment]
@ceciliaITpub closing for now. Please re-open if you continue to experience issues.
