### ISSUE TITLE
Building Types Chart (Floodplain) Incorrect

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-profiles#443]
I didn't find an issue for this, but we need to re-run labs-community-_data_ for building_type_buildings. The problem however is that one of the queries is throwing a `504 Gateway Time-out` - it seems the query is long-running, making it a candidate for Carto's Batch Queries feature (issue for this here: https://github.com/NYCPlanning/labs-community-data/issues/1). Once this is re-run, these charts can be updated.

**Comment by allthesignals** [comment]
We re-ran this query, which took longer because we needed to set up and use the batch query API (too many queries were timing out). 

Here are the results, Allan will review:
[flood-analysis.csv.zip](https://github.com/NYCPlanning/labs-community-portal/files/1407785/flood-analysis.csv.zip)

**Comment by allanz-dcp** [comment]
Additional edits to the Floodplain section of the CD Profiles below:
1) Within Building Count and Dwelling Unit Count Typologies, change "Public Facilities, Institutions, Other" to "All Other Buildings (includes certain 1-2 family cooperative lots)" 
2) Within "Basements in Floodplain" correct typo: "_sturcture_ with Unknown Basement Type" to "_structure_ with Unknown Basement Type"
3)  Floodplain indicators table: 2010 Population figures should include thousand separator commas.

**Comment by hannahkates** [comment]
Closing, since this issue is no longer relevant. The floodplain charts are consuming tables directly from Carto now, not using the json files in labs-community-data. The building typologies have also now been updated to a different scheme.
