### ISSUE TITLE
Update NPM Packages

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-profiles#458]
`npm outdated` yields:
<img width="759" alt="labs-community-portal_ _-bash_ _104x50_and_update_npm_packages_ _issue__458_ _nycplanning_labs-community-portal" src="https://user-images.githubusercontent.com/1833820/33953926-c457feb2-e004-11e7-94b9-a98ff7147e78.png">

**Comment by allthesignals** [comment]
Working on this here: https://github.com/NYCPlanning/labs-community-portal/issues/454.
