### ISSUE TITLE
Waterfront Chart ToDos

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-profiles#465]
- [x] Loading Spinner (when switching)
- [ ] Check out invalid geom error in Queens 14
- [ ] Recalculate the buildings and units columns in the main table
- [x] Update the other 3 charts to use a within query
- [x] Basements should only reference landuse = 1
- [ ] 2050 Toggle
- [ ] Sturcture
- [ ] Add tooltip for population label in table

**Comment by hannahkates** [comment]
Closing since these haven't come up in recent discussion on floodplain charts
