### ISSUE TITLE
Neighborhood Studies & Plans not loading

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-profiles#475]
In the projects section, the list of recent or ongoing studies for each CD is not loading.

**Comment by chriswhong** [comment]
Not sure what happened here, but the API call to get studies and plans was not firing because the computed property it lives in was never called, because the syntax in the handlebars was wrong.  Hotfixed in d3a41d274dfd45f569ae2600e922ac29850946f4
