### ISSUE TITLE
197-a Plans not displaying

### ISSUE THREAD

**Issue by jorgeh01** [NYCPlanning/labs-community-profiles#477]
#### What happened instead: 

No plans show up -- i.e. BK 6, BK 1.

#### How to reproduce this bug: 

Visit BK 6 profile, go to Projects, 197-a Plans and no plans is displayed. 

#### Browser(s) and Device(s) observed on:

Chrome

**Comment by kerrygathers** [comment]
@chriswhong Can we get this fixed this week? It's pertinent to a meeting I have coming up this week or next.

**Comment by chriswhong** [comment]
Closed by 82ace99fc77c1b48d3c44e2878f416f81ec18347
