### ISSUE TITLE
Facility points not appearing on map

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-profiles#482]
#### What should happen:
Facility points from Facilities Explorer should appear in Facilities map 

#### What happened instead:
Facility points do not appear
![image](https://user-images.githubusercontent.com/29131366/36555724-d6a6bc30-17d0-11e8-9adf-348f16e5db61.png)

#### Browser(s) and Device(s) observed on:
Chrome

**Comment by chriswhong** [comment]
This is due to changing table names yesterday, we'll get it fixed right now...

**Comment by chriswhong** [comment]
Updated and deployed.
