### ISSUE TITLE
Add additional about text

### ISSUE THREAD

**Issue by pichot** [NYCPlanning/labs-community-profiles#556]
The communications group would like to add some text toe the Community District Profiles app - https://communityprofiles.planning.nyc.gov/
 
Please add the following text after the first paragraph right before the search box:
 
> New York City’s community boards were created by local law in 1975, and each represents a community district. Community boards create opportunities for active participation in public decision making; they help to articulate community needs; shape the services provided to neighborhoods; and they reflect New York City’s remarkable diversity. Community districts range in size from less than 900 acres to almost 15,000 acres, and in population from a little more than 50,000 residents to more than 200,000.

**Comment by allthesignals** [comment]
Hi @mchinplanning - the template for this view can be found here: https://github.com/NYCPlanning/labs-community-profiles/blob/develop/app/templates/index.hbs.

Please add the text and style it as you see fit!
