### ISSUE TITLE
Update top 3 CD needs data

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-community-profiles#582]
Planning Coordination needs to update the data on top 3 CD needs in the big master data table: community_district_profiles. They will provide an updated version of the spreadsheet containing updated contents for those three columns (son_issue_1, son_issue_2, son_issue_3).

Link to old data table that will be superseded: https://nycplanning-web.carto.com/u/planninglabs/tables/community_district_profiles_v201910

**Comment by bfreeds** [comment]
@hannahkates here's the CSV provided by Christopher P.
[community_district_profiles_v202002_Master File.csv.zip](https://github.com/NYCPlanning/labs-community-profiles/files/4262392/community_district_profiles_v202002_Master.File.csv.zip)
