### ISSUE TITLE
Undefined land use category for some lots in MapPLUTO map

### ISSUE THREAD

**Issue by cfpolack** [NYCPlanning/labs-community-profiles#593]
#### What should happen:
All lots in the land use map on CD Profiles should be categorized into one of the MapPLUTO land use categories by color.

#### What happened instead:
Some lots are displayed with black fill and display the label 'undefined' for land use type. This black fill is not represented by any of the bars in the map key.

#### How to reproduce this bug:
1. Click on Manhattan CD 1
2. Scroll down to Built Environment section, Land Use
3. Some lots including Ellis Island display with black fill and show 'undefined' land use type

#### Browser(s) and Device(s) observed on:
Chrome on Mac

**Comment by trbmcginnis** [comment]
![Screen Shot 2020-08-13 at 3.34.35 PM.png](https://images.zenhubusercontent.com/5ca36b1555cfe32f2f66b411/f9265bd0-c1a3-41fa-904c-6d109cb5c762)
