### ISSUE TITLE
Update tooltips for July 2020 data

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-community-profiles#595]
Related to https://github.com/NYCPlanning/labs-layers-api/issues/194

Many of the tooltips on Community Profiles are already out of date and/or will be made inaccurate with the new July 2020 data. EDM will provide a list of all the data source versions used for the July 2020 data - i.e. which version of ACS, which version of MapPLUTO, etc.

Here is one glaring example of old text that hasn't been updated:
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/aedbf6a4-9e10-47e4-a17d-78406b2cf544)

We need to thoroughly examine the text in each tooltip in the app and update the data source versions so they are correct.

**Comment by cfpolack** [comment]
July 2020 update: Change text to "2014-2018 Estimate"

<img width="729" alt="Screen Shot 2020-07-30 at 5 17 56 PM" src="https://user-images.githubusercontent.com/12699064/89052924-6aa98780-d324-11ea-9720-db7db26113c1.png">

**Comment by cfpolack** [comment]
**July 2020 update**
Crime indicator: Change text to "in 2019"

<img width="388" alt="Screen Shot 2020-07-30 at 5 18 28 PM" src="https://user-images.githubusercontent.com/12699064/89052974-7eed8480-d324-11ea-8dbe-01ce9983c83a.png">

**Comment by trbmcginnis** [comment]
https://raw.githubusercontent.com/NYCPlanning/db-community-profiles/master/cdprofiles_build/version.env
