### ISSUE TITLE
Update land use chart to consume %s directly from data source

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-community-profiles#601]
Currently, the land use chart is populated with percentages that the app calculates using MapPLUTO data. This calculation is using a flawed methodology that has raised some data quality concerns.

EDM is providing the % land use breakdown in the source data table. We should update the code for the land use chart to eliminate the calculation and directly consume the numbers EDM will provide.

https://github.com/NYCPlanning/labs-community-profiles/blob/develop/app/components/land-use-chart.js#L22

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/674ad3cf-3fba-4e28-9e1a-9e7c9aa89e96)

**Comment by trbmcginnis** [comment]
This issue is dependent on labs-layers-api issue [196](https://github.com/NYCPlanning/labs-layers-api/issues/196)

**Comment by trbmcginnis** [comment]
Waiting on confirmation from EDM about where to find these fields -- doesn't seem like they're on the new community_district_profiles dataset
