### ISSUE TITLE
Broken Land Use Chart

### ISSUE THREAD

**Issue by cfpolack** [NYCPlanning/labs-community-profiles#621]
#### What should happen:
Land Use section should display chart showing breakdown of lot area within the Community District by Land Use type from PLUTO. 

#### What happened instead:
Land Use chart does not display for any districts.

Appears to be related to a failing SQL query appearing in the browser console:
`GET https://planninglabs.carto.com/api/v2/sql?q=%20%20%20%20SELECT%20%20%20%20%20%20borocd,%20%20%20%20%20%20pct_lot_area_commercial_office,%20%20%20%20%20%20pct_lot_area_industrial_manufacturing,%20%20%20%20%20%20pct_lot_area_mixed_use,%20%20%20%20%20%20pct_lot_area_open_space,%20%20%20%20%20%20pct_lot_area_other_no_data,%20%20%20%20%20%20pct_lot_area_parking,%20%20%20%20%20%20pct_lot_area_public_facility_institution,%20%20%20%20%20%20pct_lot_area_res_1_2_family_bldg,%20%20%20%20%20%20pct_lot_area_res_multifamily_elevator,%20%20%20%20%20%20pct_lot_area_res_multifamily_walkup,%20%20%20%20%20%20pct_lot_area_transportation_utility,%20%20%20%20%20%20pct_lot_area_vacant%20%20%20%20FROM%20community_district_profiles%20%20%20%20WHERE%20borocd%20=%20%27108%27%20%20%20%20&format=json   400`

<img width="1303" alt="Screen Shot 2021-01-25 at 10 52 28 AM" src="https://user-images.githubusercontent.com/12699064/105731043-fa5b7780-5efc-11eb-8384-ee0e0d5f5162.png">

#### How to reproduce this bug:

1. Click on any Community District
2. Scroll down to Built Environment section
3. Land use chart does not load and is displayed as empty white space

#### Browser(s) and Device(s) observed on:

Chrome on Mac

**Comment by horatiorosa** [comment]
@cfpolack [cfpolack](https://github.com/cfpolack) it took 1000 years to get to this but the bug fix is in. Thanks for surfacing this to us!

**Comment by horatiorosa** [comment]
Notes: If this should reoccur before we migrate to the EDM data pipeline, we may have to update the aliases using this script found here: https://github.com/NYCPlanning/labs-layers-api/tree/develop/scripts/aliased-views.
