### ISSUE TITLE
Refactor land-use-chart component

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-profiles#66]
This is becoming a candidate for refactoring. Some thoughts:

- It's _probably_ an anti-pattern (data down, actions up) that the component makes an network request for data, then passes it down. This should be reconsidered: the route should be responsible for pulling data. Exceptions to this rule make sense, for example, when we're loading a component that grabs data for 3rd party services like a twitter feed. At the very least, a promise of some form should be handed down to the component.

- This branches off the above thought, but should we keep the network request in the component, we probably need a more sophisticated way of getting the component to know promise state. The ES6 'fetch' function doesn't have a way of conveying _synchronously_ the status of the promise. Consider ember-deferrable-content or Ember concurrency. The latter will terminate an in-progress network transition during multiple network requests, which eliminates awkwardness. 

- consider c3, or extending c3, which is unit tested and has large community support, to handle the chart. Bespoke solution is more customizable (maybe - depends on where needs are finalized), but maybe presents unintended consequences and other gotchas in later weeks.

**Comment by allthesignals** [comment]
Some discussion about this: https://www.youtube.com/watch?v=y7aHMj6VVJY&feature=youtu.be&t=1129.

**Comment by jorgeh01** [comment]
@allthesignals ???

**Comment by allthesignals** [comment]
@jorgeh01 hmmm not sure what you mean?

**Comment by jorgeh01** [comment]
@allthesignals not sure what i mean either :/ LU chart looks fine to me

**Comment by hannahkates** [comment]
This will be eliminated by #601
