### ISSUE TITLE
Information banner is blocking map controls and displacing the application header also blocking map content

### ISSUE THREAD

**Issue by horatiorosa** [NYCPlanning/labs-community-profiles#701]
#### What should happen:
Banner and header should not block content and be "sticky with page content scrolling underneath them.

#### What happened instead:
User interview email sign up banner  is displacing the header and blocking map controls
<img width="1190" alt="Screenshot 2024-01-04 at 2 15 48 PM" src="https://github.com/NYCPlanning/labs-community-profiles/assets/11340947/1b02d451-861d-4de4-81b6-0e61a0b7ed8d">

<img width="1182" alt="Screenshot 2024-01-04 at 2 15 29 PM" src="https://github.com/NYCPlanning/labs-community-profiles/assets/11340947/d186be64-59d7-47d3-9b99-c826d13d2632">

<img width="1248" alt="Screenshot 2024-01-04 at 2 45 47 PM" src="https://github.com/NYCPlanning/labs-community-profiles/assets/11340947/95277a62-a4f4-444b-876e-2c1679aad3e8">

#### How to reproduce this bug:

1. visit https://communityprofiles.planning.nyc.gov/
2. hide info a banner to see blocked content
3. scroll page, hide banner to see header displacement

**Comment by pratishta** [comment]
As James mentioned, we ended our sign-up time so I'm going to remove the banner to return the page to its previous state.
